'''
Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fibonacci():
	fibonacci_list = []
	value_1 = 
	value_2 = 
	while i < 4000000:
		accumulator += i

		0 + 1 = 1
		1 + 2 = 3
		2 + 3 = 5
		3 + 5 = 8
		5 + 8 = 13
		8 + 13 = 21

		set_1 = 1
		set_2 = 2
		sum_value = set_1 + set_2
		3 = 1 + 2

		sum_value = set_1 + set_2

		x + y = z
		y + z = a
		z + a = b

		sum_value = value_1 + value_2
		